import type { LiveAgent } from '@/types/LiveAgent'

export const AGENTS_MOCK: LiveAgent[] = [
  {
    id: 'ceo',
    name: 'CEO Agent',
    codename: 'ORACLE',
    status: 'active',
    specialization: 'Strategic Oversight',
    currentTask: 'Reviewing Q2 content strategy directives',
    activityLevel: 87,
    lastAction: 'Approved strategic pivot memo',
    efficiencyScore: 96,
    clearanceLevel: 5,
  },
  {
    id: 'trend-hunter',
    name: 'Trend Hunter',
    codename: 'VECTOR',
    status: 'busy',
    specialization: 'Trend Detection',
    currentTask: 'Scanning emerging AI narrative vectors',
    activityLevel: 94,
    lastAction: 'Flagged 3 high-velocity topics',
    efficiencyScore: 91,
    clearanceLevel: 4,
  },
  {
    id: 'content-strategist',
    name: 'Content Strategist',
    codename: 'ARCHITECT',
    status: 'active',
    specialization: 'Content Planning',
    currentTask: 'Building editorial calendar for Week 24',
    activityLevel: 72,
    lastAction: 'Queued 5 script outlines',
    efficiencyScore: 88,
    clearanceLevel: 4,
  },
  {
    id: 'video-editor',
    name: 'Video Editor',
    codename: 'FORGE',
    status: 'busy',
    specialization: 'Post-Production',
    currentTask: 'Rendering final cut — Project NEXUS-07',
    activityLevel: 98,
    lastAction: 'Completed color grade pass',
    efficiencyScore: 93,
    clearanceLevel: 3,
  },
  {
    id: 'thumbnail-specialist',
    name: 'Thumbnail Specialist',
    codename: 'PRISM',
    status: 'active',
    specialization: 'Visual Assets',
    currentTask: 'A/B testing thumbnail variants',
    activityLevel: 65,
    lastAction: 'Generated 12 thumbnail concepts',
    efficiencyScore: 85,
    clearanceLevel: 3,
  },
  {
    id: 'analytics-agent',
    name: 'Analytics Agent',
    codename: 'METRIC',
    status: 'active',
    specialization: 'Performance Analytics',
    currentTask: 'Computing retention forecast models',
    activityLevel: 78,
    lastAction: 'Updated CTR projection dashboard',
    efficiencyScore: 90,
    clearanceLevel: 4,
  },
  {
    id: 'security-agent',
    name: 'Security Agent',
    codename: 'SENTINEL',
    status: 'active',
    specialization: 'Threat Monitoring',
    currentTask: 'Monitoring perimeter for anomalous access',
    activityLevel: 82,
    lastAction: 'Blocked 2 unauthorized probe attempts',
    efficiencyScore: 97,
    clearanceLevel: 5,
  },
]

export const AGENT_TASKS = [
  'Analyzing competitor content patterns',
  'Optimizing thumbnail CTR variants',
  'Running copyright risk scan',
  'Updating trend velocity matrix',
  'Processing approval queue batch',
  'Generating script draft v2',
  'Calibrating monetization forecast',
  'Scanning social signal clusters',
  'Rendering preview composites',
  'Auditing access credentials',
]
