import type { ApprovalItem } from '@/types/Approval'

export const APPROVALS_MOCK: ApprovalItem[] = [
  {
    id: 'apr-001',
    title: 'Publish: AI OS Deep Dive — Episode 12',
    module: 'Content Lab',
    requestedBy: 'Content Strategist',
    status: 'pending',
    priority: 'high',
    createdAt: Date.now() - 3600000,
    summary: 'Final video render ready for publication. Awaiting commander approval.',
  },
  {
    id: 'apr-002',
    title: 'Deploy: Trend Radar Algorithm v3.2',
    module: 'Trend Radar',
    requestedBy: 'Trend Hunter',
    status: 'pending',
    priority: 'critical',
    createdAt: Date.now() - 7200000,
    summary: 'Updated velocity detection model requires authorization before live deployment.',
  },
  {
    id: 'apr-003',
    title: 'Budget Allocation: Q2 Ad Spend',
    module: 'Analytics Center',
    requestedBy: 'CEO Agent',
    status: 'reviewing',
    priority: 'high',
    createdAt: Date.now() - 10800000,
    summary: 'Proposed $48K reallocation across 3 content verticals.',
  },
  {
    id: 'apr-004',
    title: 'Thumbnail Set: Cyberpunk Series Batch',
    module: 'Content Lab',
    requestedBy: 'Thumbnail Specialist',
    status: 'pending',
    priority: 'medium',
    createdAt: Date.now() - 14400000,
    summary: '12 thumbnail variants ready for A/B test authorization.',
  },
  {
    id: 'apr-005',
    title: 'Security Policy: External API Access',
    module: 'Security Center',
    requestedBy: 'Security Agent',
    status: 'pending',
    priority: 'critical',
    createdAt: Date.now() - 18000000,
    summary: 'New integration endpoint requires elevated clearance approval.',
  },
  {
    id: 'apr-006',
    title: 'Simulation Run: Viral Content Model',
    module: 'Simulation Center',
    requestedBy: 'Analytics Agent',
    status: 'approved',
    priority: 'medium',
    createdAt: Date.now() - 86400000,
    summary: 'Monte Carlo simulation authorized for 10K iterations.',
  },
  {
    id: 'apr-007',
    title: 'Agent Dispatch: Multi-Channel Campaign',
    module: 'Agent Command',
    requestedBy: 'CEO Agent',
    status: 'rejected',
    priority: 'low',
    createdAt: Date.now() - 172800000,
    summary: 'Rejected — insufficient trend confidence score.',
  },
  {
    id: 'apr-008',
    title: 'Script Approval: JARVIS Breakdown Video',
    module: 'Content Lab',
    requestedBy: 'Content Strategist',
    status: 'approved',
    priority: 'high',
    createdAt: Date.now() - 259200000,
    summary: 'Script cleared for production pipeline.',
  },
]
