import type { SimulationCenterData } from '@/types/SimulationCenter'

export const SIMULATION_CENTER_MOCK: SimulationCenterData = {
  scenario: {
    id: 'sim-2847',
    name: 'VIRAL_SHORT_FORM_LAUNCH',
    status: 'complete',
    runId: 'QX-8842-A',
    contentType: 'Short-Form Video',
    platform: 'Multi-Channel',
  },
  opportunityScore: {
    id: 'opportunity-score',
    label: 'Opportunity Score',
    value: 87,
    maxValue: 100,
    displayValue: '87',
    confidence: 91,
    variant: 'accent',
    meta: 'MARKET WINDOW OPEN',
  },
  predictedViews: {
    id: 'predicted-views',
    label: 'Predicted Views',
    value: 78,
    maxValue: 100,
    displayValue: '2.4M',
    confidence: 84,
    variant: 'blue',
    meta: '30-DAY FORECAST',
  },
  predictedRetention: {
    id: 'predicted-retention',
    label: 'Predicted Retention',
    value: 72,
    maxValue: 100,
    displayValue: '72%',
    confidence: 79,
    variant: 'purple',
    meta: 'AVG WATCH-THROUGH',
  },
  predictedRevenue: {
    id: 'predicted-revenue',
    label: 'Predicted Revenue',
    value: 65,
    maxValue: 100,
    displayValue: '$48.2K',
    confidence: 76,
    variant: 'cyan',
    meta: 'NET PROJECTED',
  },
  competitionScore: {
    id: 'competition-score',
    label: 'Competition Score',
    value: 58,
    maxValue: 100,
    displayValue: '58',
    confidence: 82,
    variant: 'magenta',
    meta: 'SATURATION INDEX',
  },
  copyrightRisk: {
    id: 'copyright-risk',
    label: 'Copyright Risk',
    value: 24,
    maxValue: 100,
    displayValue: 'LOW',
    confidence: 88,
    variant: 'red',
    meta: 'CLEARANCE LIKELY',
  },
  monetizationScore: {
    id: 'monetization-score',
    label: 'Monetization Score',
    value: 81,
    maxValue: 100,
    displayValue: '81',
    confidence: 85,
    variant: 'blue',
    meta: 'YIELD POTENTIAL',
  },
}
