import type { TrendRadarData } from '@/types/TrendRadar'

export const TREND_RADAR_MOCK: TrendRadarData = {
  trendingTopics: [
    {
      id: 'topic-1',
      name: 'AI Content Automation',
      category: 'Operations',
      volume: 28400,
      changePercent: 34.2,
      rank: 1,
    },
    {
      id: 'topic-2',
      name: 'Neural Video Synthesis',
      category: 'Media',
      volume: 22100,
      changePercent: 28.7,
      rank: 2,
    },
    {
      id: 'topic-3',
      name: 'Short-Form Viral Hooks',
      category: 'Social',
      volume: 19850,
      changePercent: 19.4,
      rank: 3,
    },
    {
      id: 'topic-4',
      name: 'Multimodal Search',
      category: 'Discovery',
      volume: 16200,
      changePercent: 15.1,
      rank: 4,
    },
    {
      id: 'topic-5',
      name: 'Creator Economy Tokens',
      category: 'Monetization',
      volume: 13750,
      changePercent: 11.8,
      rank: 5,
    },
  ],
  trendVelocities: [
    {
      id: 'velocity-1',
      topicName: 'AI Content Automation',
      velocity: 92,
      direction: 'rising',
      peakWindow: '48H',
    },
    {
      id: 'velocity-2',
      topicName: 'Neural Video Synthesis',
      velocity: 78,
      direction: 'rising',
      peakWindow: '72H',
    },
    {
      id: 'velocity-3',
      topicName: 'Short-Form Viral Hooks',
      velocity: 64,
      direction: 'stable',
      peakWindow: '24H',
    },
    {
      id: 'velocity-4',
      topicName: 'Multimodal Search',
      velocity: 51,
      direction: 'rising',
      peakWindow: '96H',
    },
    {
      id: 'velocity-5',
      topicName: 'Creator Economy Tokens',
      velocity: 33,
      direction: 'declining',
      peakWindow: '120H',
    },
  ],
  competitionLevels: [
    {
      id: 'competition-1',
      topicName: 'AI Content Automation',
      level: 'high',
      competitorCount: 148,
      saturationIndex: 82,
    },
    {
      id: 'competition-2',
      topicName: 'Neural Video Synthesis',
      level: 'medium',
      competitorCount: 76,
      saturationIndex: 58,
    },
    {
      id: 'competition-3',
      topicName: 'Short-Form Viral Hooks',
      level: 'critical',
      competitorCount: 312,
      saturationIndex: 94,
    },
    {
      id: 'competition-4',
      topicName: 'Multimodal Search',
      level: 'low',
      competitorCount: 29,
      saturationIndex: 31,
    },
    {
      id: 'competition-5',
      topicName: 'Creator Economy Tokens',
      level: 'medium',
      competitorCount: 54,
      saturationIndex: 47,
    },
  ],
  growthPotentials: [
    {
      id: 'growth-1',
      topicName: 'Multimodal Search',
      score: 91,
      timeframe: 'Q3 2026',
      confidence: 88,
    },
    {
      id: 'growth-2',
      topicName: 'Neural Video Synthesis',
      score: 84,
      timeframe: 'Q2 2026',
      confidence: 79,
    },
    {
      id: 'growth-3',
      topicName: 'AI Content Automation',
      score: 76,
      timeframe: 'Q2 2026',
      confidence: 72,
    },
    {
      id: 'growth-4',
      topicName: 'Short-Form Viral Hooks',
      score: 58,
      timeframe: 'Q3 2026',
      confidence: 61,
    },
    {
      id: 'growth-5',
      topicName: 'Creator Economy Tokens',
      score: 42,
      timeframe: 'Q4 2026',
      confidence: 55,
    },
  ],
  heatMap: {
    rows: 6,
    cols: 8,
    cells: [
      { row: 0, col: 0, intensity: 0.15 },
      { row: 0, col: 1, intensity: 0.35 },
      { row: 0, col: 2, intensity: 0.55, label: 'AI_OPS' },
      { row: 0, col: 3, intensity: 0.72 },
      { row: 0, col: 4, intensity: 0.48 },
      { row: 0, col: 5, intensity: 0.22 },
      { row: 0, col: 6, intensity: 0.18 },
      { row: 0, col: 7, intensity: 0.1 },
      { row: 1, col: 0, intensity: 0.28 },
      { row: 1, col: 1, intensity: 0.62 },
      { row: 1, col: 2, intensity: 0.88, label: 'VIDEO_AI' },
      { row: 1, col: 3, intensity: 0.91 },
      { row: 1, col: 4, intensity: 0.67 },
      { row: 1, col: 5, intensity: 0.41 },
      { row: 1, col: 6, intensity: 0.25 },
      { row: 1, col: 7, intensity: 0.12 },
      { row: 2, col: 0, intensity: 0.42 },
      { row: 2, col: 1, intensity: 0.78 },
      { row: 2, col: 2, intensity: 0.95, label: 'VIRAL' },
      { row: 2, col: 3, intensity: 0.84 },
      { row: 2, col: 4, intensity: 0.59 },
      { row: 2, col: 5, intensity: 0.38 },
      { row: 2, col: 6, intensity: 0.2 },
      { row: 2, col: 7, intensity: 0.08 },
      { row: 3, col: 0, intensity: 0.18 },
      { row: 3, col: 1, intensity: 0.44 },
      { row: 3, col: 2, intensity: 0.63 },
      { row: 3, col: 3, intensity: 0.71, label: 'SEARCH' },
      { row: 3, col: 4, intensity: 0.52 },
      { row: 3, col: 5, intensity: 0.33 },
      { row: 3, col: 6, intensity: 0.16 },
      { row: 3, col: 7, intensity: 0.05 },
      { row: 4, col: 0, intensity: 0.1 },
      { row: 4, col: 1, intensity: 0.26 },
      { row: 4, col: 2, intensity: 0.39 },
      { row: 4, col: 3, intensity: 0.47 },
      { row: 4, col: 4, intensity: 0.35, label: 'TOKEN' },
      { row: 4, col: 5, intensity: 0.21 },
      { row: 4, col: 6, intensity: 0.12 },
      { row: 4, col: 7, intensity: 0.04 },
      { row: 5, col: 0, intensity: 0.06 },
      { row: 5, col: 1, intensity: 0.14 },
      { row: 5, col: 2, intensity: 0.22 },
      { row: 5, col: 3, intensity: 0.28 },
      { row: 5, col: 4, intensity: 0.19 },
      { row: 5, col: 5, intensity: 0.11 },
      { row: 5, col: 6, intensity: 0.07 },
      { row: 5, col: 7, intensity: 0.03 },
    ],
  },
}
